
spring:
  application:
    name: lms_system
  datasource:
    url: "jdbc:postgresql://localhost:5432/lms_system"
    username: postgres
    password: 123
  jpa: 
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': false
server:
  port: 8081
  servlet:
    context-path: /lms
  error: 
    include-message: always